second-commit
Senkid12/Sprint_4 pull request #1
Opened 2023-11-22 12:08 UTC by Senkid12

Четвертый спринт курса "Автоматизатор тестирования на java".
В тесте для создания заказа был использован WebDriverManager для FireFox

2023-11-23 15:19 UTC, pavel-ulan requested changes
Неплохо. Есть несколько минорных замечаний которые надо поправить, но в целом работа довольно хорошая =)

2023-11-23 15:19 UTC, pavel-ulan commented on pom.xml
> +          <target>8</target>
**надо исправить**
а почему отсылка к компилятору 8й версии? По условиям задания должна быть 11-я =)

2023-11-23 15:19 UTC, pavel-ulan commented on src/main/java/org/yandex/prakrikum/pageObject/HomePage.java
> +    private final By downOrderButton = By.xpath("//*[@id=\"root\"]/div/div[1]/div[4]/div[2]/div[5]/button");
**надо исправить**
очень очень некрасивый локатор, состоящий из абсолютного пути =/

Старайся не использовать локаторы состоящие только из пути (не важно относительный/абсолютный). Как правило всегда можно подобрать другой, более читаемый, локатор. Такие локаторы плохо читаются, по ним непонятно, куда они указывают и если что-то меняется в верстке, то они ломаются и могут или никуда не вести или, что еще хуже, возвращать совершенно другой элемент.

2023-11-23 15:19 UTC, pavel-ulan commented on src/main/java/org/yandex/prakrikum/pageObject/HomePage.java
> +        new WebDriverWait(driver, Duration.ofSeconds(10)).until(driver -> (driver.findElement(homePageHeader).getText() != null && !driver.findElement(homePageHeader).getText().isEmpty()));
мне просто интересно, а какую разницу ты ожидаешь от 
driver.findElement(homePageHeader).getText() != null 
и
!driver.findElement(homePageHeader).getText().isEmpty() ?

2023-11-23 15:19 UTC, pavel-ulan commented on src/main/java/org/yandex/prakrikum/pageObject/PageAboutCustomer.java
> +    private final By nextButton = By.xpath("//*[@id=\"root\"]/div/div[2]/div[3]/button");
**надо исправить**
локаторы надо править

2023-11-23 15:19 UTC, pavel-ulan commented on src/main/java/org/yandex/prakrikum/pageObject/constants/ScooterColors.java
**хорошо**
клево, что использовал enumы и класс констант. И в целом здорово, что как-то систематизируешь используемые данные. Это хорошее решение, старайся придерживаться этого подхода.

2023-11-23 15:19 UTC, pavel-ulan commented on src/test/java/org/yandex/prakrikum/pageObject/CreateOrderTest.java
> +        assertTrue("Ожидамый результат = " + expectedStatusOrder + ".Фактический = " + objPageAboutScooter.getPopUpWindowAfterOrder() + "!",objPageAboutScooter.getPopUpWindowAfterOrder().contains(exp
**можно лучше**
тебе не обязательно писать "Ожидамый результат" и ".Фактический ". Если проверка не пройдет, она и так выведет какой был ожидаемый, а какой фактический. Так что ты просто сделал работу за нее =)

2023-11-23 19:20 UTC, Senkid12 commented
Учел замечания в работе во втором коммите

2023-11-24 12:12 UTC, pavel-ulan approved these changes
Да, отличненько 👍

2023-11-24 12:12 UTC, pavel-ulan commented on src/main/java/org/yandex/prakrikum/pageObject/PageAboutScooter.java
> +    private final By popUpWindowAfterOrder = By.xpath("/html/body/div/div/div[2]/div[5]");
**можно лучше**
всеравно оставляешь абсолют-пасс локаторы. Все же старайся этого не делать

2023-11-24 12:15 UTC, Senkid12 commented on src/main/java/org/yandex/prakrikum/pageObject/PageAboutScooter.java
> +    private final By popUpWindowAfterOrder = By.xpath("/html/body/div/div/div[2]/div[5]");
Принял, спасибо за ревью кода)

2023-11-26 10:24 UTC, merged